### ISSUE TITLE
Potential deadlock in async_client

### ISSUE THREAD

**Issue by alex-bluesman** [eclipse-paho/paho.mqtt.rust#239]
Hello everybody.

I've found very strange issue and would like to ask for your feedback.

### Test environment description

I have tens of unit tests for my library. Each test is executed in parallel, and each each test runs MQTT broker on unique port and create Paho client to this broker.

### Problem description

If I run my tests in the loop (like `while true; do cargo test; done`. I see quite often hangs like certain amount of tests are running more than 60 seconds. Number of hanging tests is always variable, also different tests hang every time.

### Debugging report

I was able to collect the following information from lldb:

![image](https://github.com/user-attachments/assets/ad1e263c-15cc-4999-b0e3-535e7adeb5c3)

so I see that all the tests actually waiting for mutex. After inspecting the backtrace for threads I've found suspisious place:

![image](https://github.com/user-attachments/assets/ffacbb5c-bf08-45f1-a41d-7ff8b28353f3)

After further investigation I have now a guess, that the following problem happens:
- In frame 21 `MQTTAsync_cycle()` locks `mqttasync_mutex`
- When we failed to connect (frame 19), we call callback `on_failure()` from Rust world. This callback creates local variable: `let tok = Token::from_raw(context);`, and this variable through internal members contains `AsyncClient` instance. So when end of scope `on_failure()` reached - Rust triggers drop chain which finally leads to `MQTTAsync_destroy` (frame 5).
- Destroy tries to lock the same mutex and deadlock happens. As consequence - all the clients within these process are deadlocked as well :-/

Will appreciate any comment! Have a nice day!

**Comment by alex-bluesman** [comment]
Hello again, found a problem inside project library. If initial connection fails we spawn reconnect routine in tokyo::spawn(), but don't kill it on Drop.  Sorry for the noise!

**Comment by fpagliughi** [comment]
No worries... Keep posting any issues. I'm about to start working on some updates, so the timing is good to get any bug fixes in.
